# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwMailingRemove.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mwMailingRemove(object):
    def setupUi(self, mwMailingRemove):
        mwMailingRemove.setObjectName("mwMailingRemove")
        mwMailingRemove.resize(1154, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/document_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mwMailingRemove.setWindowIcon(icon)
        mwMailingRemove.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mwMailingRemove)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 321, 43))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.leFirstName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.leFirstName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leFirstName.setObjectName("leFirstName")
        self.gridLayout.addWidget(self.leFirstName, 1, 0, 1, 1)
        self.lblFirstName = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.gridLayout.addWidget(self.lblFirstName, 0, 0, 1, 1)
        self.lblLastName = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.gridLayout.addWidget(self.lblLastName, 0, 1, 1, 1)
        self.leLastName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.leLastName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leLastName.setObjectName("leLastName")
        self.gridLayout.addWidget(self.leLastName, 1, 1, 1, 1)
        self.leZipCode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.leZipCode.setMaximumSize(QtCore.QSize(50, 16777215))
        self.leZipCode.setText("")
        self.leZipCode.setMaxLength(5)
        self.leZipCode.setAlignment(QtCore.Qt.AlignCenter)
        self.leZipCode.setObjectName("leZipCode")
        self.gridLayout.addWidget(self.leZipCode, 1, 2, 1, 1)
        self.lblZipCode = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblZipCode.setFont(font)
        self.lblZipCode.setObjectName("lblZipCode")
        self.gridLayout.addWidget(self.lblZipCode, 0, 2, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(350, 40, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.tblResults = QtWidgets.QTableWidget(self.centralwidget)
        self.tblResults.setGeometry(QtCore.QRect(20, 80, 1121, 192))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tblResults.setFont(font)
        self.tblResults.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblResults.setAlternatingRowColors(True)
        self.tblResults.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblResults.setRowCount(0)
        self.tblResults.setColumnCount(12)
        self.tblResults.setObjectName("tblResults")
        self.tblResults.horizontalHeader().setStretchLastSection(True)
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setGeometry(QtCore.QRect(20, 510, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnRemove.setFont(font)
        self.btnRemove.setObjectName("btnRemove")
        self.gbNotes = QtWidgets.QGroupBox(self.centralwidget)
        self.gbNotes.setGeometry(QtCore.QRect(20, 420, 691, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbNotes.setFont(font)
        self.gbNotes.setObjectName("gbNotes")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gbNotes)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 651, 52))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vboxNotes = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vboxNotes.setContentsMargins(0, 0, 0, 0)
        self.vboxNotes.setObjectName("vboxNotes")
        self.rbtnMailingNote = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtnMailingNote.setChecked(True)
        self.rbtnMailingNote.setObjectName("rbtnMailingNote")
        self.vboxNotes.addWidget(self.rbtnMailingNote)
        self.rbtnPostNote = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rbtnPostNote.setObjectName("rbtnPostNote")
        self.vboxNotes.addWidget(self.rbtnPostNote)
        self.lstNotes = QtWidgets.QListWidget(self.centralwidget)
        self.lstNotes.setGeometry(QtCore.QRect(20, 280, 1121, 121))
        self.lstNotes.setObjectName("lstNotes")
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        self.lblLogo.setGeometry(QtCore.QRect(980, 10, 171, 51))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/image/pixi_logo_new.png"))
        self.lblLogo.setObjectName("lblLogo")
        mwMailingRemove.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mwMailingRemove)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 21))
        self.menubar.setObjectName("menubar")
        mwMailingRemove.setMenuBar(self.menubar)

        self.retranslateUi(mwMailingRemove)
        QtCore.QMetaObject.connectSlotsByName(mwMailingRemove)

    def retranslateUi(self, mwMailingRemove):
        _translate = QtCore.QCoreApplication.translate
        mwMailingRemove.setWindowTitle(_translate("mwMailingRemove", "Remove From Mailing List"))
        self.lblFirstName.setText(_translate("mwMailingRemove", "First Name:"))
        self.lblLastName.setText(_translate("mwMailingRemove", "Last Name:"))
        self.lblZipCode.setText(_translate("mwMailingRemove", "Zip Code:"))
        self.btnSearch.setText(_translate("mwMailingRemove", "Submit"))
        self.btnRemove.setText(_translate("mwMailingRemove", "Remove"))
        self.gbNotes.setTitle(_translate("mwMailingRemove", "Select Note"))
        self.rbtnMailingNote.setText(_translate("mwMailingRemove", "We received the postcard back from the post office as undeliverable.  I have marked the acct as do not mail."))
        self.rbtnPostNote.setText(_translate("mwMailingRemove", "Per the customer’s request to be removed from the mailing list we have marked the account as Do Not Mail."))

import image_rc
